# Generated by Django 5.1.2 on 2024-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.CharField(max_length=50),
        ),
    ]
